export const lists = [
  {
    id: "001",
    image: "../images/SOLO.jpg",
    post: "Chairman",
    name: "Sen. Solomon Diri",
    age: "40",
    profession: "Civil Servant",
    stste: "Rivers",
  },
  {
    id: "002",
    image: "../images/ogolo.png",
    post: "Vice Chairman",
    name: "Mr. Ibisnye Ogolo",
    age: "36",
    profession: "Public Servant",
    stste: "Rivers",
  },
  {
    id: "003",
    image: "./images/gogo.png",
    post: "Secretary",
    name: "Mr. Degogo Jaja",
    age: "30",
    profession: "Businesman",
    stste: "Rivers",
  },
  {
    id: "004",
    image: "./images/boma.jpg",
    post: "Asst. Secretary",
    name: "Mr. Boma Pepple",
    age: "30",
    profession: "Civil Servant",
    stste: "Rivers",
  },
  {
    id: "005",
    image: "./images/anna.png",
    post: "Treasurer",
    name: "Mrs. Ann Opusunju",
    age: "50",
    profession: "Civil Servant",
    stste: "Rivers",
  },
  {
    id: "006",
    image: "./images/gift.jpg",
    post: "Financial Secretary",
    name: "Mrs Gift Jaja",
    age: "50",
    profession: "Civil Servant",
    stste: "Rivers",
  },
  {
    id: "007",
    image: "./images/enyinna.jpg",
    post: "Welfare Officer 1",
    name: "Mr. Enyinna Pepple",
    age: "40",
    profession: "Civil Servant",
    stste: "Rivers",
  },
  {
    id: "008",
    image: "./images/comfort.jpg",
    post: "Welfare Officer 2",
    name: "Mrs. Comfort Tolofari",
    age: "40",
    profession: "Civil Servant",
    stste: "Rivers",
  },
  {
    id: "009",
    image: "./images/brown.jpg",
    post: "P.R.O",
    name: "Mr. Dieprinye Brown",
    age: "40",
    profession: "Engineer",
    stste: "Rivers",
  },
  {
    id: "010",
    image: "./images/Alali.png",
    post: "Provost",
    name: "Mr. Alali Goodhead",
    age: "40",
    profession: "Engineer",
    stste: "rivers",
  },
  {
    id: "011",
    image: " ./images/ogolo.png",
    post: "Auditor 1",
    name: "Mr. Ibisnye Ogolo",
    age: "40",
    profession: "Accountant",
    stste: "Rivers",
  },
  {
    id: "012",
    image: "./images/stella.jpg",
    post: "Auditor 2",
    name: "Mrs. Stella Diri",
    age: "40",
    profession: "Accountant",
    state: "Rivers",
  },
];

export const roaster = [
  {
    sn: 1,
    groupDate: "GROUP 2 / Feb. 4th",
    name: "MR IBISONYE KALA-OGOLO",
    phoneNo: "080 6117 1718",
    remarks: "---------",
  },
  {
    sn: 2,
    groupDate: "GROUP 2 / Feb. 4th",
    name: "MR BLESSING JAJA",
    phoneNo: "080 3263 1443",
    remarks: "---------",
  },
  {
    sn: 3,
    groupDate: "GROUP 2 / Feb. 4th",
    name: "MRS GIFT JAJA",
    phoneNo: "081 3432 3859",
    remarks: "---------",
  },
  {
    sn: 4,
    groupDate: "GROUP 3 / Mar. 3rd",
    name: "MR LAMBERT S.JAJA",
    phoneNo: "080 3054 3355",
    remarks: "---------",
  },
  {
    sn: 5,
    groupDate: "GROUP 3 / Mar. 3rd",
    name: "MR SOFRI JOHN-AFFRICA",
    phoneNo: "080 6583 2707",
    remarks: "---------",
  },
  {
    sn: 6,
    groupDate: "GROUP 3 / Mar. 3rd",
    name: "MRS GLADYS BROWN",
    phoneNo: "081 8429 1969",
    remarks: "---------",
  },
  {
    sn: 7,
    groupDate: "GROUP 4 / Apr. 7th",
    name: "SEN. S.J. TOLOFARI",
    phoneNo: "080 3776 7733",
    remarks: "---------",
  },
  {
    sn: 8,
    groupDate: "GROUP 4 / Apr. 7th",
    name: " MRS. COMFORT TOLOFARI",
    phoneNo: "080 3482 4511",
    remarks: "---------",
  },
  {
    sn: 9,
    groupDate: "GROUP 5 / May 5th",
    name: " MR BOMA PEPPLE",
    phoneNo: "080 6815 5715",
    remarks: "---------",
  },
  {
    sn: 10,
    groupDate: "GROUP 5 / May 5th",
    name: " MR OBINNA OPUSUNJU",
    phoneNo: "081 0895 5438",
    remarks: "---------",
  },
  {
    sn: 11,
    groupDate: "GROUP 5 / May 5th",
    name: " MRS PATRICIA JOHNAFRICA",
    phoneNo: "081 3602 9515",
    remarks: "---------",
  },
  {
    sn: 12,
    groupDate: "GROUP 6 / Jun. 2nd",
    name: " MR ENYINNA PEPPLE ",
    phoneNo: " 070 3911 5959",
    remarks: "---------",
  },
  {
    sn: 13,
    groupDate: "GROUP 6 / Jun. 2nd",
    name: " MR GODDY M. JAJA ",
    phoneNo: "080 6866 8933",
    remarks: "---------",
  },
  {
    sn: 14,
    groupDate: "GROUP 6 / Jun. 2nd",
    name: " MR ALALI GOODHEAD ",
    phoneNo: "080 3718 8411",
    remarks: "---------",
  },
  {
    sn: 15,
    groupDate: "GROUP 7 / Jul. 7th",
    name: " SEN. SOLOMON BROWN ",
    phoneNo: "080 3740 9195",
    remarks: "---------",
  },
  {
    sn: 16,
    groupDate: "GROUP 7 / Jul. 7th",
    name: " MRS. NKECHI BROWN ",
    phoneNo: "0803 277 2600",
    remarks: "---------",
  },
  {
    sn: 17,
    groupDate: "GROUP 8 / Aug. 4th ",
    name: " SEN. C.T.D. EPELLE ",
    phoneNo: "080 3310 0471",
    remarks: "---------",
  },
  {
    sn: 18,
    groupDate: "GROUP 8 / Aug. 4th ",
    name: " MRS IFY C.T.D. EPELLE ",
    phoneNo: "090 3633 0350",
    remarks: "---------",
  },
  {
    sn: 19,
    groupDate: "GROUP 8 / Aug. 4th ",
    name: " MISS ALICE URANTA ",
    phoneNo: "080 3743 5238",
    remarks: "---------",
  },
  {
    sn: 20,
    groupDate: "GROUP 9 / Aug. 4th ",
    name: " ELDER SAMUEL BROWN ",
    phoneNo: " 080 6240 8612",
    remarks: "---------",
  },
  {
    sn: 21,
    groupDate: "GROUP 9 / Sep. 8th ",
    name: " MRS CELINA BROWN ",
    phoneNo: " 070 6843 6450 ",
    remarks: "---------",
  },
  {
    sn: 22,
    groupDate: "GROUP 10 / Sep. 8th ",
    name: " MR DAGOGO E. JAJA ",
    phoneNo: " 080 6380 6706 ",
    remarks: "---------",
  },
  {
    sn: 23,
    groupDate: "GROUP 10 / Sep. 8th ",
    name: " MR DIEPRINYE BROWN ",
    phoneNo: " 081 3802 6138 ",
    remarks: "---------",
  },
  {
    sn: 24,
    groupDate: "GROUP 10 / Sep. 8th ",
    name: "  MR OBICHERE PEPPLE ",
    phoneNo: " 080 3718 ",
    remarks: "---------",
  },
  {
    sn: 25,
    groupDate: "GROUP 11 / Nov. 3rd ",
    name: "  MRS ANN OPUSUNJU  ",
    phoneNo: "080 6926 6779 ",
    remarks: "---------",
  },
  {
    sn: 26,
    groupDate: "GROUP 11 / Nov. 3rd ",
    name: "  MR ATIDO PEPPLE  ",
    phoneNo: "080 7700 9370",
    remarks: "---------",
  },
  {
    sn: 27,
    groupDate: "GROUP 11 / Nov. 3rd ",
    name: "  MR EUGENE JAJA  ",
    phoneNo: "080 6455 9177",
    remarks: "---------",
  },
  {
    sn: 28,
    groupDate: "GROUP 12 / Dec. 8th ",
    name: "  SEN DIRI SOLOMON  ",
    phoneNo: "080 3750 3775",
    remarks: "---------",
  },
  {
    sn: 29,
    groupDate: "GROUP 12 / Dec. 8th ",
    name: "  MRS STELLA DIRI  ",
    phoneNo: "081 4876 8526",
    remarks: "---------",
  },
];

export const menuItems = [
  {
    title: "Marketing",
    path: "/marketing",
    clasName: "dropdownList",
  },
  {
    title: "Production",
    path: "/production",
    clasName: "dropdownList",
  },
  {
    title: "Sales",
    path: "/Sales",
    clasName: "dropdownList",
  },
  {
    title: "Purchase",
    path: "/purchase",
    clasName: "dropdownList",
  },
];
